name: bad_people
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_markdown: ^0.7.6+2
  flutter_staggered_animations: ^1.1.1
  http: ^1.3.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.13.1  # Check for latest version

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"  # Path to your icon



flutter:
  uses-material-design: true
